#pragma once

#include <cstdint>
#include <filesystem>
#include <functional>
#include <memory>
#include <optional>
#include <string>
#include <vector>

#include "../Core/Settings/AudioSettings.hpp"

namespace heritage::audio {

using AudioHandle = std::uint64_t;
inline constexpr AudioHandle kInvalidAudioHandle = 0;

enum class AudioBus
{
    Music,
    Effects,
    Ambience,
    UI,
    Voice
};

// Backend-independent coordinates use Heritage's world convention:
// +X right, +Y up and +Z forward. Keeping these types out of XAudio2 headers
// lets module/runtime code remain portable when another backend is added.
struct AudioVector3
{
    float x = 0.0f;
    float y = 0.0f;
    float z = 0.0f;
};

struct AudioListenerState
{
    AudioVector3 position;
    AudioVector3 velocity;
    AudioVector3 forward{ 0.0f, 0.0f, 1.0f };
    AudioVector3 up{ 0.0f, 1.0f, 0.0f };
};

struct AudioEmitterState
{
    AudioVector3 position;
    AudioVector3 velocity;
    float minimumDistanceMeters = 1.0f;
    float maximumDistanceMeters = 150.0f;
};

// Geometry-derived propagation for one source/listener pair. The backend
// combines this with ordinary source volume, distance, panning and Doppler.
// Reflection delay is the excess path arrival time, not an arbitrary effect
// preset chosen by the vehicle definition.
struct AcousticPropagationState
{
    float directGain = 1.0f;
    float directOpenness = 1.0f;
    float earlyReflectionGain = 0.0f;
    float earlyReflectionDelaySeconds = 0.0f;
    float lateReverbGain = 0.0f;
};

// A seamless mono floating-point waveform generated by an engine subsystem.
// Generated clips are cached by key and shared by every matching vehicle.
struct GeneratedMonoAudio
{
    std::uint32_t sampleRate = 48000;
    std::vector<float> samples;
};

const char* audioBusName(AudioBus bus);
std::optional<AudioBus> parseAudioBus(const std::string& name);

// Native audio service used by Heritage Engine and exposed to module Lua.
//
// The current Windows backend uses XAudio2 and intentionally begins with
// PCM/IEEE-float WAV and OGG/Vorbis files. The public API is platform-neutral so
// another backend can be added later without changing module scripts.
class AudioSystem
{
public:
    AudioSystem();
    ~AudioSystem();

    AudioSystem(const AudioSystem&) = delete;
    AudioSystem& operator=(const AudioSystem&) = delete;

    bool initialize(std::string& message);
    void shutdown();
    void update(bool applicationFocused);

    bool isAvailable() const;
    std::string backendName() const;
    const std::string& lastError() const;

    AudioHandle playOneShot(
        const std::filesystem::path& path,
        AudioBus bus = AudioBus::Effects,
        float volume = 1.0f,
        float pitch = 1.0f);

    // AUDIO01 authoring path: decode this file for this playback only instead
    // of inserting it into the production clip cache. Engine Sound Lab rewrites
    // the same preview filename whenever a filter slider changes, so caching it
    // would replay stale audio and leak authoring revisions into the fleet cache.
    AudioHandle playOneShotUncached(
        const std::filesystem::path& path,
        AudioBus bus = AudioBus::Effects,
        float volume = 1.0f,
        float pitch = 1.0f);

    AudioHandle playLoop(
        const std::filesystem::path& path,
        AudioBus bus = AudioBus::Ambience,
        float volume = 1.0f,
        float pitch = 1.0f);

    AudioHandle playGeneratedLoop(
        const std::string& cacheKey,
        const GeneratedMonoAudio& audio,
        AudioBus bus = AudioBus::Effects,
        float volume = 1.0f,
        float pitch = 1.0f);

    // Invokes the factory only when the shared generated clip is not cached.
    // This avoids resynthesizing identical layers as fleet LOD realizes voices.
    AudioHandle playGeneratedLoopCached(
        const std::string& cacheKey,
        const std::function<GeneratedMonoAudio()>& factory,
        AudioBus bus = AudioBus::Effects,
        float volume = 1.0f,
        float pitch = 1.0f);

    // Shares the same bounded generated-clip cache as procedural loops but
    // submits the clip once. Vehicle limiter/overrun events use this path so
    // an engine definition is synthesized once, not once per event or car.
    AudioHandle playGeneratedOneShotCached(
        const std::string& cacheKey,
        const std::function<GeneratedMonoAudio()>& factory,
        AudioBus bus = AudioBus::Effects,
        float volume = 1.0f,
        float pitch = 1.0f);

    bool stop(AudioHandle handle);
    void stopAll();
    void stopBus(AudioBus bus);
    bool isPlaying(AudioHandle handle) const;
    std::size_t activeVoiceCount() const;
    std::size_t cachedAudioBytes() const;

    bool setHandleVolume(AudioHandle handle, float volume);
    bool setHandlePitch(AudioHandle handle, float pitch);
    bool setHandleSpatial(AudioHandle handle, const AudioEmitterState& emitter);
    bool setHandleLowPass(AudioHandle handle, float openness);
    bool setHandleAcoustics(
        AudioHandle handle,
        const AcousticPropagationState& acoustics);

    void setListener(const AudioListenerState& listener);
    const AudioListenerState& listener() const;

    void applySettings(const heritage::settings::AudioSettings& settings);
    const heritage::settings::AudioSettings& settings() const;

    void setMasterVolume(float volume);
    float masterVolume() const;
    void setBusVolume(AudioBus bus, float volume);
    float busVolume(AudioBus bus) const;
    void setMuteWhenUnfocused(bool enabled);
    bool muteWhenUnfocused() const;

private:
    struct Impl;
    std::unique_ptr<Impl> m_impl;
};

} // namespace heritage::audio
