#pragma once

// Generated by Tools/GenerateBuildIdentity.ps1. Do not edit by hand.
namespace heritage::diagnostics::generated {
inline constexpr const char* kMilestone = "29L";
inline constexpr const char* kGitCommit = "c9f426089305";
inline constexpr const char* kGitDirty = "dirty";
inline constexpr const char* kGeneratedUtc = "2026-08-07T16:29:08.380Z";
inline constexpr const char* kRequestedConfiguration = "Release";
}