#pragma once

// Generated by Tools/GenerateBuildIdentity.ps1. Do not edit by hand.
namespace heritage::diagnostics::generated {
inline constexpr const char* kMilestone = "LIVETRACK06-100M-ONLY-GPU-HYDRO";
inline constexpr const char* kGitCommit = "unavailable";
inline constexpr const char* kGitDirty = "unknown";
inline constexpr const char* kGeneratedUtc = "2026-08-20T06:50:09.597Z";
inline constexpr const char* kRequestedConfiguration = "Release";
}