#pragma once

// Generated by Tools/GenerateBuildIdentity.ps1. Do not edit by hand.
namespace heritage::diagnostics::generated {
inline constexpr const char* kMilestone = "29J.6A";
inline constexpr const char* kGitCommit = "f94187f525b8";
inline constexpr const char* kGitDirty = "dirty";
inline constexpr const char* kGeneratedUtc = "2026-08-07T15:27:32.969Z";
inline constexpr const char* kRequestedConfiguration = "Release";
}