-- Deterministic VehicleDefinitionV2 export serialization.
-- Kept separate so persistence/export changes do not inflate schema or validation code.

local function SerializeVehicleDefinitionValue(value, indent)
    local valueType = type(value)
    if valueType == "string" then return string.format("%q", value) end
    if valueType == "number" or valueType == "boolean" then
        return tostring(value)
    end
    if valueType ~= "table" then return "nil" end

    local nextIndent = indent .. "    "
    local lines = { "{" }
    local numericCount = #value
    for index = 1, numericCount do
        table.insert(lines, nextIndent
            .. SerializeVehicleDefinitionValue(value[index], nextIndent) .. ",")
    end
    local keys = {}
    for key, _ in pairs(value) do
        if type(key) ~= "number" then table.insert(keys, key) end
    end
    table.sort(keys, function(left, right) return tostring(left) < tostring(right) end)
    for _, key in ipairs(keys) do
        local encodedKey = string.match(key, "^[%a_][%w_]*$")
            and key or ("[" .. string.format("%q", key) .. "]")
        table.insert(lines, nextIndent .. encodedKey .. " = "
            .. SerializeVehicleDefinitionValue(value[key], nextIndent) .. ",")
    end
    table.insert(lines, indent .. "}")
    return table.concat(lines, "\n")
end

function SerializeVehicleDefinitionV2(definition)
    return "-- Generated by Heritage Vehicle Workshop\nreturn "
        .. SerializeVehicleDefinitionValue(definition, "") .. "\n"
end
