$studioProjectPath = Join-Path $Root "Engine\HeritageEngine\HeritageStudio\HeritageStudio.vcxproj"
$studioAppPath = Join-Path $Root "Engine\HeritageEngine\HeritageStudio\HeritageStudioApp.cpp"
$studioHeaderPath = Join-Path $Root "Engine\HeritageEngine\HeritageStudio\HeritageStudioApp.hpp"
$studioMainPath = Join-Path $Root "Engine\HeritageEngine\HeritageStudio\main.cpp"
$studioScenePreviewPath = Join-Path $Root "Engine\HeritageEngine\HeritageStudio\StudioScenePreview.cpp"
$studioBuildPath = Join-Path $Root "Tools\01_BuildAndRunHeritageStudio.cmd"
$studioDocPath = Join-Path $Root "Docs\Heritage-Studio.md"
$solutionPath = Join-Path $Root "Engine\HeritageEngine\HeritageEngine.slnx"
$codeAuditPath = Join-Path $Root "Tools\Diagnostics\CodeHealthAudit.ps1"
$labCppPath = Join-Path $Root "Engine\HeritageEngine\Audio\Lab\EngineSoundCaptureLab.cpp"
$dspCppPath = Join-Path $Root "Engine\HeritageEngine\Audio\Lab\EngineSoundLabDsp.cpp"
$vehicleCameraHeaderPath = Join-Path $Root "Engine\HeritageEngine\Camera\VehicleCameraController.hpp"
$vehicleCameraCppPath = Join-Path $Root "Engine\HeritageEngine\Camera\VehicleCameraController.cpp"
$luaCameraBindingsPath = Join-Path $Root "Engine\HeritageEngine\Core\Modules\LuaBindings\LuaCameraBindings.cpp"
$engineSimulationPath = Join-Path $Root "Engine\HeritageEngine\HeritageEngine\Runtime\EngineSimulation.cpp"

$studioProject = ReadText $studioProjectPath
$studioApp = ReadText $studioAppPath
$studioHeader = ReadText $studioHeaderPath
$studioMain = ReadText $studioMainPath
$studioScenePreview = ReadText $studioScenePreviewPath
$studioBuild = ReadText $studioBuildPath
$solution = ReadText $solutionPath
$codeAudit = ReadText $codeAuditPath
$labCpp = ReadText $labCppPath
$dspCpp = ReadText $dspCppPath
$vehicleCameraHeader = ReadText $vehicleCameraHeaderPath
$vehicleCameraCpp = ReadText $vehicleCameraCppPath
$luaCameraBindings = ReadText $luaCameraBindingsPath
$engineSimulation = ReadText $engineSimulationPath


# Match the version Heritage Studio actually writes, not historical compatibility
# strings/comments. Milestone validators use minimum versions so future additive
# format revisions do not make older completed milestones fail.
function HasWrittenFormatVersionAtLeast([string]$Text, [string]$Magic, [int]$Minimum)
{
    if ([string]::IsNullOrEmpty($Text)) { return $false }
    $pattern = 'out\s*<<\s*"' + [regex]::Escape($Magic) + '\s+([0-9]+)\\n"'
    foreach ($match in [regex]::Matches($Text, $pattern))
    {
        $version = 0
        if ([int]::TryParse($match.Groups[1].Value, [ref]$version) -and $version -ge $Minimum)
        {
            return $true
        }
    }
    return $false
}

Check ((Test-Path $studioProjectPath) -and (Test-Path $studioAppPath) -and (Test-Path $studioHeaderPath) -and (Test-Path $studioMainPath)) "STUDIO01 HeritageStudio standalone native application sources exist"
Check ($solution.Contains('HeritageStudio/HeritageStudio.vcxproj')) "STUDIO01 HeritageStudio is an active project in the HeritageEngine solution"
Check ($studioProject.Contains('<TargetName>HeritageStudio</TargetName>') -and $studioProject.Contains('<SubSystem>Windows</SubSystem>') -and $studioProject.Contains('EngineSoundCaptureLab.cpp') -and $studioProject.Contains('EngineSoundLabDsp.cpp')) "STUDIO01 project emits HeritageStudio.exe and owns the Engine Sound Lab implementation"
Check ($studioApp.Contains('Workspace::Scene') -and $studioApp.Contains('Workspace::Race') -and $studioApp.Contains('Workspace::Traffic') -and $studioApp.Contains('Workspace::Weather') -and $studioApp.Contains('Workspace::Vehicle') -and $studioApp.Contains('Workspace::Audio')) "STUDIO01 unified executable exposes Scene/Race/Traffic/Weather/Vehicle/Audio workspaces"
Check ($studioApp.Contains('CAPTURE CALIBRATION SAMPLE') -and $studioApp.Contains('CAPTURE CURRENT TARGET') -and $studioApp.Contains('RAW A/B') -and $studioApp.Contains('REAR / EXHAUST') -and $studioApp.Contains('DRIVER CABIN')) "STUDIO01 Audio workspace exposes capture and perspective audition workflow"
Check ($studioApp.Contains('Presence reduction') -and $studioApp.Contains('Pulse-edge softening') -and $studioApp.Contains('Stock muffling') -and $studioApp.Contains('Cabin damping') -and $studioApp.Contains('Occlusion preview')) "STUDIO01 Audio workspace exposes non-destructive source/cabin/environment shaping controls"
Check ($labCpp.Contains('AUDCLNT_STREAMFLAGS_LOOPBACK') -and $labCpp.Contains('capture_manifest.csv') -and $dspCpp.Contains('processEngineSoundStereo')) "STUDIO01 Engine Sound Lab keeps WASAPI loopback, bank manifest and DSP processing"
Check ($codeAudit.Contains('$activeNativeProjectRelatives') -and $codeAudit.Contains("'HeritageStudio\HeritageStudio.vcxproj'")) "STUDIO01 code-health audit treats HeritageStudio as an active native project"
Check ((Test-Path $studioBuildPath) -and $studioBuild.Contains('Build\Studio\Release\HeritageStudio.exe') -and $studioBuild.Contains('HeritageStudio.vcxproj')) "STUDIO01 dedicated build helper builds and launches only HeritageStudio"
Check (Test-Path $studioDocPath) "STUDIO01 standalone authoring architecture is documented"

# STUDIO02 Audio Assistant — assisted/non-destructive sound authoring.
Check ($studioApp.Contains('AUTO PEUGEOT 206 RC STOCK') -and $studioApp.Contains('AUTO CLEAN ENGINE-SIM RAW') -and $studioApp.Contains('RESET NEUTRAL') -and $studioApp.Contains('RAW CAPTURE ANALYSIS')) "STUDIO02 Audio Assistant exposes one-click Peugeot/cleanup presets and raw analysis"
Check ($studioApp.Contains('JUMP TO FIRST MISSING') -and $studioApp.Contains('Quality gate') -and $studioApp.Contains('Skip already captured cells') -and $studioApp.Contains('countCompletedCaptureTargets')) "STUDIO02 Peugeot bank is resumable and quality-gated"
Check ($dspCpp.Contains('analyzeEngineSoundStereo') -and $dspCpp.Contains('autoTuneEngineSoundProfile') -and $dspCpp.Contains('EngineSoundPreset::Peugeot206RCStock') -and $dspCpp.Contains('goertzelPower')) "STUDIO02 dependency-free analyzer and adaptive preset DSP are implemented"
Check ($labCpp.Contains('m_lastAnalysis = analyzeEngineSoundStereo') -and $labCpp.Contains('bankCaptureExists') -and $labCpp.Contains('bankCapturePath')) "STUDIO02 capture owner analyzes raw audio and exposes persisted bank completion"

# STUDIO03 Vehicle Character Designer — preserve deep per-vehicle acoustic identity.
Check ($studioApp.Contains('VEHICLE CHARACTER DESIGNER') -and $studioApp.Contains('STOCK AIRBOX') -and $studioApp.Contains('OPEN FILTER') -and $studioApp.Contains('ITB / SHORT')) "STUDIO03 exposes intake architecture authoring beyond one-click cleanup"
Check ($studioApp.Contains('STOCK MUFFLED') -and $studioApp.Contains('SPORT CAT-BACK') -and $studioApp.Contains('OPEN / RACE') -and $studioApp.Contains('Tailpipe brightness')) "STUDIO03 exposes distinct exhaust topology / character authoring"
Check ($studioApp.Contains('LIGHT HATCH') -and $studioApp.Contains('GT / INSULATED') -and $studioApp.Contains('STRIPPED / RACE') -and $studioApp.Contains('Window open preview')) "STUDIO03 exposes cabin-construction archetypes and leakage preview"
Check ($dspCpp.Contains('profile.combustionPunch') -and $dspCpp.Contains('profile.metallicCharacter') -and $dspCpp.Contains('profile.airboxDamping') -and $dspCpp.Contains('profile.exhaustRasp') -and $dspCpp.Contains('profile.windowOpenPreview')) "STUDIO03 character controls materially alter DSP rather than being UI-only"
Check ($labCpp.Contains('write("combustionPunch"') -and $labCpp.Contains('write("airboxDamping"') -and $labCpp.Contains('write("exhaustRasp"') -and $labCpp.Contains('write("windowOpenPreview"')) "STUDIO03 per-vehicle character DNA persists in .hacoustic profiles"

# STUDIO04 Audio UI readability — slider meaning must remain visible rather than clipped off-screen.
Check ($studioApp.Contains('beginParameterTable') -and $studioApp.Contains('DESCRIPTION') -and $studioApp.Contains('describedSlider') -and $studioApp.Contains('SetTooltip')) "STUDIO04 Audio controls expose persistent descriptions plus hover help"
Check ($studioApp.Contains('CollapsingHeader("ENGINE CORE / COMBUSTION"') -and $studioApp.Contains('CollapsingHeader("RAW / ELECTRIC HARSHNESS"') -and $studioApp.Contains('CollapsingHeader("CABIN / WORLD PREVIEW"')) "STUDIO04 dense audio controls are split into collapsible readable groups"

# STUDIO05 Core authoring foundation — Studio now owns persistent racing/free-roam authoring data.
$studioAuthoringHeaderPath = Join-Path $Root "Engine\HeritageEngine\HeritageStudio\Authoring\StudioAuthoringData.hpp"
$studioAuthoringCppPath = Join-Path $Root "Engine\HeritageEngine\HeritageStudio\Authoring\StudioAuthoringData.cpp"
$studioAuthoringHeader = ReadText $studioAuthoringHeaderPath
$studioAuthoringCpp = ReadText $studioAuthoringCppPath
Check ((Test-Path $studioAuthoringHeaderPath) -and (Test-Path $studioAuthoringCppPath) -and $studioProject.Contains('Authoring\StudioAuthoringData.cpp')) "STUDIO05 persistent authoring data owner is compiled into HeritageStudio"
Check ($studioAuthoringHeader.Contains('SceneObjectType') -and $studioAuthoringHeader.Contains('RaceMarkerType') -and $studioAuthoringHeader.Contains('TrafficNodeType') -and $studioAuthoringHeader.Contains('WeatherWorld') -and $studioAuthoringHeader.Contains('VehicleStudioProfile')) "STUDIO05 data model covers scene/race/traffic/weather/vehicle authoring"
Check ($studioAuthoringCpp.Contains('HSCENE 1') -and $studioAuthoringCpp.Contains('HRACE 1') -and $studioAuthoringCpp.Contains('HROAD 1') -and $studioAuthoringCpp.Contains('HWEATHER 1') -and $studioAuthoringCpp.Contains('HVEHICLEAUTHOR 1')) "STUDIO05 authoring workspaces serialize explicit Heritage asset formats"
Check ($studioApp.Contains('saveScene') -and $studioApp.Contains('Player Spawn') -and $studioApp.Contains('Audio Zone') -and ($studioApp.Contains('RACE OBJECTS') -or $studioApp.Contains('RACE OBJECT INSPECTOR')) -and $studioApp.Contains('+ PIT BOX') -and $studioApp.Contains('+ AI WET LINE')) "STUDIO05 scene and race authoring have editable object workflows"
Check ($studioApp.Contains('ROAD GRAPH NODES') -and $studioApp.Contains('+ INTERSECTION') -and $studioApp.Contains('+ TRAFFIC LIGHT') -and $studioApp.Contains('+ PARKING') -and $studioApp.Contains('Overtaking allowed')) "STUDIO05 free-roam traffic workspace authors lane/rule infrastructure"
Check ($studioApp.Contains('SAVE WEATHER') -and $studioApp.Contains('Starting surface wetness') -and $studioApp.Contains('SAVE VEHICLE AUTHORING') -and $studioApp.Contains('Eligible for free-roam traffic')) "STUDIO05 weather and vehicle metadata are editable/persistent"
Check ($studioApp.Contains('Orbitron-SemiBold.ttf') -and $studioApp.Contains('AddFontFromFileTTF') -and $studioApp.Contains('g_headingFont')) "STUDIO05 Heritage Studio uses the repository Orbitron SemiBold heading font with runtime fallback"
Check ($studioApp.Contains('Workspace::Assets') -and $studioApp.Contains('ASSET BROWSER') -and $studioApp.Contains('COPY PATH')) "STUDIO05 unified Studio includes a first-class Racing United asset browser"


# STUDIO06 Interactive 3D authoring — spatial content is placeable/pickable in Studio.
Check ($studioApp.Contains('3D VIEWPORT') -and $studioApp.Contains('prepareInteractiveViewport') -and $studioApp.Contains('MMB orbit') -and $studioApp.Contains('Shift+MMB pan')) "STUDIO06 shared 3D viewport exposes orbit/pan/zoom authoring navigation"
Check ($studioApp.Contains('drawMoveGizmo') -and $studioApp.Contains('m_viewGizmoAxis') -and $studioApp.Contains('m_viewSnapM')) "STUDIO06 selected authoring points expose XYZ move gizmo and snapping"
Check ($studioApp.Contains('PLACE PLAYER') -and $studioApp.Contains('PLACE VEHICLE') -and $studioApp.Contains('Placed scene object in 3D viewport')) "STUDIO06 Scene workspace supports direct ground-plane placement"
Check (($studioApp.Contains('3D RACE LAYOUT') -or $studioApp.Contains('3D VENUE / ROUTE PREVIEW')) -and $studioApp.Contains('AI RACE LINE') -and $studioApp.Contains('drawOrderedPolyline') -and $studioApp.Contains('Placed race object in 3D viewport')) "STUDIO06 Race workspace visualizes/places checkpoints, grids, pits and AI-line nodes in 3D"
Check ($studioApp.Contains('3D ROAD GRAPH') -and $studioApp.Contains('TrafficPlacementToolbar') -and $studioApp.Contains('Placed traffic node in 3D viewport')) "STUDIO06 Traffic workspace visualizes/places road graph nodes in 3D"

# STUDIO07 Blender 5.2 interaction/layout compatibility for community authoring.
Check ($studioApp.Contains('Ctrl+PgUp/PgDn workspaces') -and $studioApp.Contains('WorkspaceTabs') -and $studioApp.Contains('ImGuiKey_PageUp') -and $studioApp.Contains('ImGuiKey_PageDown')) "STUDIO07 uses Blender-style top workspace strip and workspace cycling"
Check ($studioApp.Contains('MMB orbit') -and $studioApp.Contains('Shift+MMB pan') -and $studioApp.Contains('Ctrl+MMB') -and $studioApp.Contains('ImGuiKey_Keypad1') -and $studioApp.Contains('ImGuiKey_Keypad3') -and $studioApp.Contains('ImGuiKey_Keypad7') -and $studioApp.Contains('ImGuiKey_Keypad5')) "STUDIO07 viewport navigation follows Blender 5.2 defaults"
Check ($studioApp.Contains('ImGuiKey_G') -and $studioApp.Contains('ImGuiKey_R') -and $studioApp.Contains('ImGuiKey_S') -and $studioApp.Contains('X/Y/Z constrain') -and $studioApp.Contains('LMB/Enter confirm') -and $studioApp.Contains('RMB/Esc cancel')) "STUDIO07 Scene transform modal follows Blender G/R/S and axis constraint semantics"
Check ($studioApp.Contains('Shift+A') -and $studioApp.Contains('HeritageAddMenu') -and $studioApp.Contains('Shift+D') -and $studioApp.Contains('Blender X/Delete')) "STUDIO07 Blender add/duplicate/delete conventions extend to game authoring objects"
Check ($studioApp.Contains('SceneOutliner') -and $studioApp.Contains('SceneProperties') -and $studioApp.Contains('GAME AUTHORING / PLAYTEST') -and $studioApp.Contains('OUTLINER') -and $studioApp.Contains('PROPERTIES')) "STUDIO07 Scene Layout mirrors Blender viewport/outliner/properties editor composition plus game strip"
Check ($studioApp.Contains('ImGuiKey_T') -and $studioApp.Contains('ImGuiKey_N') -and $studioApp.Contains('ITEM  [N]') -and $studioApp.Contains('m_viewOrthographic')) "STUDIO07 viewport toolbar/sidebar toggles and perspective/orthographic authoring state are implemented"

# STUDIO08 real GLB/PBR world viewport — authoring overlays sit on the actual scene.
$studioScenePreviewHeaderPath = Join-Path $Root "Engine\HeritageEngine\HeritageStudio\StudioScenePreview.hpp"
$studioScenePreviewCppPath = Join-Path $Root "Engine\HeritageEngine\HeritageStudio\StudioScenePreview.cpp"
$studioScenePreviewHeader = ReadText $studioScenePreviewHeaderPath
$studioScenePreviewCpp = ReadText $studioScenePreviewCppPath
Check ((Test-Path $studioScenePreviewHeaderPath) -and (Test-Path $studioScenePreviewCppPath) -and $studioProject.Contains('StudioScenePreview.cpp')) "STUDIO08 Studio compiles a dedicated real-scene preview renderer"
Check ($studioProject.Contains('..\Graphics\Gltf\GltfBinary.cpp') -and $studioProject.Contains('..\Graphics\Mesh.cpp') -and $studioProject.Contains('..\Graphics\Texture2D.cpp')) "STUDIO08 viewport reuses Heritage GLB, mesh and texture pipeline instead of inventing a parallel asset loader"
Check ($studioScenePreviewCpp.Contains('loadGlbMesh') -and $studioScenePreviewHeader.Contains('Texture2DCache') -and $studioScenePreviewCpp.Contains('distributionGGX') -and $studioScenePreviewCpp.Contains('uMetallic') -and $studioScenePreviewCpp.Contains('uRoughness')) "STUDIO08 viewport renders GLB PBR material factors/maps"
Check ($studioScenePreviewCpp.Contains('Scene_') -and $studioScenePreviewCpp.Contains('discoverAndLoadLatest') -and $studioScenePreviewCpp.Contains('recursive_directory_iterator')) "STUDIO08 Studio discovers current Scene_*.glb under Racing United Assets/Scenes"
Check ($studioApp.Contains('drawSceneGeometryBackdrop') -and $studioApp.Contains('Scene GLB') -and $studioApp.Contains('LATEST Scene_*.glb') -and $studioApp.Contains('RELOAD GLB')) "STUDIO08 Scene workspace exposes the live world preview and reload controls"
Check ($studioApp.Contains('viewportAuthoringPoint') -and $studioApp.Contains('preview->raycast') -and $studioApp.Contains('visible scene surface')) "STUDIO08 Scene/Race/Traffic placement raycasts onto visible GLB geometry with ground-plane fallback"
Check ($studioApp.Contains('m_scenePreview->boundsCenter') -and $studioApp.Contains('m_scenePreview->boundsRadius')) "STUDIO08 Blender Home/frame-all includes imported world geometry bounds"
Check ($studioApp.Contains('ensureScenePreviewInitialized') -and $studioApp.Contains('Starting Studio in the') -and $studioApp.Contains('Audio workspace must not load the world')) "STUDIO08 real-world preview remains lazy and does not burden Audio-only authoring"

# STUDIO09 runtime scene bridge + editor-wide Orbitron typography.
Check ($studioApp.Contains('io.FontDefault = io.Fonts->AddFontFromFileTTF') -and $studioApp.Contains('kStudioRuntimeSpawnSection') -and $studioApp.Contains('saveRuntimeVehicleSpawn') -and $studioApp.Contains('RuntimeBackups')) "STUDIO09 Studio uses Orbitron as the default editor font and safely publishes Vehicle Spawn into the module entry scene"

# STUDIO10 gameplay/world event authoring and explicit road graph.
$studioGameplayRuntimePath = Join-Path $Root "Modules\RacingUnited\Scripts\Runtime\StudioGameplay.lua"
$studioGameplayGeneratedPath = Join-Path $Root "Modules\RacingUnited\Scripts\Generated\StudioGameplay.lua"
$racingUnitedMainPath = Join-Path $Root "Modules\RacingUnited\Scripts\Main.lua"
$studioGameplayRuntime = ReadText $studioGameplayRuntimePath
$racingUnitedMain = ReadText $racingUnitedMainPath
Check ($studioHeader.Contains('Workspace::Gameplay') -or $studioApp.Contains('Workspace::Gameplay')) "STUDIO10 Heritage Studio exposes a first-class GAMEPLAY workspace"
Check ($studioAuthoringHeader.Contains('RaceConfiguration') -and $studioAuthoringHeader.Contains('TrafficLink') -and $studioAuthoringHeader.Contains('GameEvent') -and $studioAuthoringHeader.Contains('WorldPoint')) "STUDIO10 authoring data owns persistent race rules, road links, events and free-roam world points"
Check ((HasWrittenFormatVersionAtLeast $studioAuthoringCpp 'HRACE' 2) -and (HasWrittenFormatVersionAtLeast $studioAuthoringCpp 'HROAD' 2) -and (HasWrittenFormatVersionAtLeast $studioAuthoringCpp 'HGAME' 1)) "STUDIO10 versioned race/road/gameplay formats are serialized"
Check ($studioApp.Contains('GENERATE MISSING GRID') -and $studioApp.Contains('AUTO LINK LANES') -and $studioApp.Contains('ADD DIRECTED LINK') -and $studioApp.Contains('DELETE SELECTED LINK')) "STUDIO10 race grid generation and automatic/manual explicit road-link authoring are implemented"
Check ($studioApp.Contains('+ STREET CIRCUIT') -and $studioApp.Contains('+ STREET SPRINT') -and $studioApp.Contains('+ GARAGE') -and $studioApp.Contains('+ SPEED TRAP') -and $studioApp.Contains('+ FAST TRAVEL')) "STUDIO10 gameplay GUI covers motorsport/clandestine events and free-roam activity/service anchors"
Check ($studioApp.Contains('validateAuthoring') -and $studioApp.Contains('VALIDATION OK') -and $studioApp.Contains('references a missing node')) "STUDIO10 cross-layer authoring validation is implemented"
Check ((Test-Path $studioGameplayRuntimePath) -and (Test-Path $studioGameplayGeneratedPath) -and $studioApp.Contains('saveRuntimeGameplay') -and $racingUnitedMain.Contains('Generated/StudioGameplay.lua') -and $racingUnitedMain.Contains('Runtime/StudioGameplay.lua')) "STUDIO10 Studio compiles authoring data to a module-owned Lua asset loaded by Racing United"
Check ($studioGameplayRuntime.Contains('GetEvent') -and $studioGameplayRuntime.Contains('GetOutgoingRoadLinks') -and $studioGameplayRuntime.Contains('GetNearestWorldPoint') -and $studioGameplayRuntime.Contains('ResolveEventRoute')) "STUDIO10 Racing United exposes runtime query helpers for authored gameplay/road/world data"


# STUDIO11 venue route/layout/session/race-director expansion.
Check ((HasWrittenFormatVersionAtLeast $studioAuthoringCpp 'HRACE' 3) -and (HasWrittenFormatVersionAtLeast $studioAuthoringCpp 'HGAME' 2) -and $studioAuthoringHeader.Contains('RaceRoute') -and $studioAuthoringHeader.Contains('RaceLayout') -and $studioAuthoringHeader.Contains('RaceSession') -and $studioAuthoringHeader.Contains('RaceControlConfiguration')) "STUDIO11 venue routes/layouts/sessions/race-director data model is serialized"
Check ($studioApp.Contains('ROUTES + CORRIDORS') -and $studioApp.Contains('LAYOUTS') -and $studioApp.Contains('SESSIONS') -and $studioApp.Contains('RACE CONTROL') -and $studioApp.Contains('PLACE ROUTE NODE ON SURFACE')) "STUDIO11 Race workspace exposes venue route, layout, session and race-control authoring"
Check ($studioApp.Contains('AUTO-SMOOTH ROUTE TANGENTS') -and $studioApp.Contains('GENERATE MISSING GRID') -and $studioApp.Contains('Safety Car') -and $studioApp.Contains('TRACK LIMIT')) "STUDIO11 venue tooling retains route smoothing, grid generation, race-control and track-limit workflows"
Check ($studioGameplayRuntime.Contains('GetRaceLayout') -and $studioGameplayRuntime.Contains('GetRouteNodes') -and $studioGameplayRuntime.Contains('GetSessionChain') -and $studioGameplayRuntime.Contains('GetRaceControl')) "STUDIO11 Racing United runtime facade exposes venue/layout/session/race-director queries"


# STUDIO12 free-roam road construction, junction control, parking, traffic population and navigation build.
Check ((HasWrittenFormatVersionAtLeast $studioAuthoringCpp 'HROAD' 3) -and $studioAuthoringHeader.Contains('RoadSpline') -and $studioAuthoringHeader.Contains('RoadSplineNode') -and $studioAuthoringHeader.Contains('RoadIntersection') -and $studioAuthoringHeader.Contains('TurnConnector') -and $studioAuthoringHeader.Contains('TrafficSignalPhase') -and $studioAuthoringHeader.Contains('ParkingStrip')) "STUDIO12 HROAD v3 owns high-level road spline/junction/signal/parking authoring"
Check ($studioApp.Contains('ROAD SPLINES') -and $studioApp.Contains('TRACE ROAD NODES') -and $studioApp.Contains('JUNCTIONS / SIGNALS') -and $studioApp.Contains('+ LEGAL TURN CONNECTOR') -and $studioApp.Contains('+ SIGNAL PHASE')) "STUDIO12 Traffic workspace exposes road tracing, intersections, legal turns and traffic-signal phases"
Check ($studioApp.Contains('PARKING / POPULATION / NAV') -and $studioApp.Contains('Rush-hour multiplier') -and $studioApp.Contains('Max active vehicles') -and $studioApp.Contains('NAVIGATION COMPILER') -and $studioApp.Contains('SYNC / COMPILE LANE GRAPH') -and $studioAuthoringCpp.Contains('AUTO_LANE_') -and $studioAuthoringCpp.Contains('compileRoadSplinesToLaneGraph')) "STUDIO12 Traffic workspace authors parking/population/navigation and compiles road splines into lane graph data"
Check ($studioApp.Contains('roadSplines = {') -and $studioApp.Contains('roadIntersections = {') -and $studioApp.Contains('turnConnectors = {') -and $studioApp.Contains('trafficSignalPhases = {') -and $studioApp.Contains('navigationBuild = {')) "STUDIO12 road-construction data is compiled into Racing United runtime Lua"
Check ($studioGameplayRuntime.Contains('GetRoad') -and $studioGameplayRuntime.Contains('GetRoadNodes') -and $studioGameplayRuntime.Contains('GetTurnConnectors') -and $studioGameplayRuntime.Contains('GetSignalPhases') -and $studioGameplayRuntime.Contains('GetNearestRoadNode') -and $studioGameplayRuntime.Contains('GetRoadLaneDescriptors') -and $studioGameplayRuntime.Contains('GetRoadNetworkSummary')) "STUDIO12 Racing United exposes runtime road/junction/navigation query helpers"


# STUDIO13 operational traffic/navigation runtime: semantic lane graph, driving rules, live signals, restrictions and streaming.
$trafficOperationsPath = Join-Path $Root "Modules\RacingUnited\Scripts\Runtime\TrafficOperations.lua"
$trafficOperations = ReadText $trafficOperationsPath
$coneCoursePath = Join-Path $Root "Modules\RacingUnited\Scripts\Runtime\ConeCourse.lua"
$coneCourse = ReadText $coneCoursePath
Check ((HasWrittenFormatVersionAtLeast $studioAuthoringCpp 'HROAD' 4) -and $studioAuthoringHeader.Contains('TrafficLinkType') -and $studioAuthoringHeader.Contains('TrafficRulesConfiguration') -and $studioAuthoringHeader.Contains('TrafficStreamingConfiguration') -and $studioAuthoringHeader.Contains('RoadRestriction')) "STUDIO13 HROAD v4 serializes semantic lane graph and operational traffic policy"
Check ($studioApp.Contains('OPERATIONS / ROUTING') -and $studioApp.Contains('Movement semantic') -and $studioApp.Contains('DRIVING / CAR-FOLLOWING RULES') -and $studioApp.Contains('TRAFFIC STREAMING SECTORS') -and $studioApp.Contains('LIVE SIGNAL CONTROLLER') -and $studioApp.Contains('+ ROAD RESTRICTION')) "STUDIO13 Traffic workspace exposes routing operations, driving rules, streaming, live signals and closures"
Check ($studioAuthoringCpp.Contains('TrafficLinkType::LaneChange') -and $studioAuthoringCpp.Contains('trafficRules.laneChangeRouteCost') -and $studioAuthoringCpp.Contains('if (!link.generated) return;') -and $studioAuthoringCpp.Contains('link.generated = true')) "STUDIO13 road compiler creates semantic lane-change edges while preserving manual graph overrides"
Check ((Test-Path $trafficOperationsPath) -and $racingUnitedMain.Contains('Runtime/TrafficOperations.lua') -and $trafficOperations.Contains('FindRoute') -and $trafficOperations.Contains('UpdateSignals') -and $trafficOperations.Contains('TryReserveIntersection') -and $trafficOperations.Contains('GetStreamingTier') -and $trafficOperations.Contains('ShouldYieldForEmergency')) "STUDIO13 Racing United runtime performs restriction-aware routing, signal control, intersection reservation, traffic streaming and emergency yielding"
Check ($studioApp.Contains('trafficRules = {') -and $studioApp.Contains('trafficStreaming = {') -and $studioApp.Contains('intersectionControllers = {') -and $studioApp.Contains('roadRestrictions = {')) "STUDIO13 operational traffic data is compiled into Racing United runtime Lua"

# STUDIO14 physical traffic-agent simulation: reusable driver/vehicle archetypes,
# car-following/lane-choice behavior, streaming agent manager and proxy vehicle factory.
$trafficAgentsPath = Join-Path $Root "Modules\RacingUnited\Scripts\Runtime\TrafficAgents.lua"
$trafficAgents = ReadText $trafficAgentsPath
Check ((HasWrittenFormatVersionAtLeast $studioAuthoringCpp 'HROAD' 5) -and $studioAuthoringHeader.Contains('TrafficAgentProfile') -and $studioAuthoringHeader.Contains('TrafficAgentSimulationConfiguration') -and $studioAuthoringHeader.Contains('TrafficAgentClass')) "STUDIO14 HROAD v5 serializes physical traffic-agent archetypes and simulation policy"
Check ($studioApp.Contains('AGENTS / SIMULATION') -and $studioApp.Contains('PHYSICAL TRAFFIC-AGENT SIMULATION') -and $studioApp.Contains('+ AGENT PROFILE') -and $studioApp.Contains('Maximum full-physics agents') -and $studioApp.Contains('Lane-change aggression') -and $studioApp.Contains('Speed-limit compliance')) "STUDIO14 Traffic workspace exposes live-agent simulation and per-archetype behavior authoring"
Check ($studioApp.Contains('trafficAgentSimulation = {') -and $studioApp.Contains('trafficAgentProfiles = {') -and $studioGameplayRuntime.Contains('GetTrafficAgentSimulationConfiguration') -and $studioGameplayRuntime.Contains('GetTrafficAgentProfile') -and $studioGameplayRuntime.Contains('GetEnabledTrafficAgentProfiles')) "STUDIO14 agent authoring data is compiled into Racing United runtime Lua and queryable through RacingGameplay"
Check ((Test-Path $trafficAgentsPath) -and $racingUnitedMain.Contains('Runtime/TrafficAgents.lua') -and $trafficAgents.Contains('ComputeCarFollowingAcceleration') -and $trafficAgents.Contains('EvaluateLaneChange') -and $trafficAgents.Contains('TryReserveIntersection') -and $trafficAgents.Contains('GetStreamingTier') -and $trafficAgents.Contains('SetVehicleFactory') -and $trafficAgents.Contains('FixedUpdateManager')) "STUDIO14 Racing United runtime owns car-following, lane choice, intersection behavior, streaming agents and a pluggable traffic-vehicle factory"
Check ($trafficAgents.Contains('Physics.CreateBody(entity, "kinematic"') -and $trafficAgents.Contains('Physics.CreateBoxCollider') -and $trafficAgents.Contains('RacingTrafficAgents.GetTelemetry') -and $trafficAgents.Contains('RacingTrafficAgents.GetAgentTelemetry')) "STUDIO14 default live-agent backend can create physical collision proxies and exposes traffic debug telemetry"
$racingUnitedLifecyclePath = Join-Path $Root 'Modules\RacingUnited\Scripts\Runtime\Lifecycle.lua'
$racingUnitedLifecycle = ReadText $racingUnitedLifecyclePath
Check ($racingUnitedMain.Contains('Runtime/TrafficAgents.lua') -and $racingUnitedLifecycle.Contains('RacingTrafficAgents.Start') -and $racingUnitedLifecycle.Contains('RacingTrafficAgents.Stop') -and $racingUnitedLifecycle.Contains('RacingTrafficAgents.FixedUpdate') -and $racingUnitedLifecycle.Contains('VehicleFixedUpdate')) "STUDIO14 traffic agents are connected to Racing United lifecycle alongside, not instead of, player vehicle simulation"


# STUDIO15 traffic integration/debugging: spatial population controls, incidents,
# weather-aware behavior, optional full Heritage Vehicle traffic and live diagnostics.
$trafficVehicleFactoryPath = Join-Path $Root "Modules\RacingUnited\Scripts\Runtime\TrafficVehicleFactory.lua"
$trafficVehicleFactory = ReadText $trafficVehicleFactoryPath
$trafficPanelPath = Join-Path $Root "Modules\RacingUnited\Scripts\UI\Prototype\TrafficPanel.lua"
$trafficPanel = ReadText $trafficPanelPath
Check ((HasWrittenFormatVersionAtLeast $studioAuthoringCpp 'HROAD' 6) -and $studioAuthoringHeader.Contains('TrafficSpawnPortal') -and $studioAuthoringHeader.Contains('TrafficDensityRegion') -and $studioAuthoringHeader.Contains('TrafficIncident') -and $studioAuthoringHeader.Contains('TrafficEnvironmentConfiguration') -and $studioAuthoringHeader.Contains('TrafficDebugConfiguration')) "STUDIO15 HROAD v6 serializes portals, density, incidents, environment response and debug policy"
Check ($studioAuthoringCpp.Contains('trafficSpawnPortals.clear(); trafficDensityRegions.clear(); trafficIncidents.clear();')) "STUDIO15 HROAD v6 load clears spatial traffic collections before deserialization"
Check ($studioApp.Contains('PORTALS / DENSITY / INCIDENTS') -and $studioApp.Contains('+ TRAFFIC PORTAL') -and $studioApp.Contains('+ DENSITY REGION') -and $studioApp.Contains('+ INCIDENT') -and $studioApp.Contains('WEATHER / VISIBILITY DRIVING RESPONSE') -and $studioApp.Contains('TRAFFIC DEBUG POLICY')) "STUDIO15 Traffic workspace authors traffic portals, density regions, incidents, weather response and diagnostics"
Check ($studioApp.Contains('Use Heritage full vehicle dynamics for FULL-tier traffic') -and $studioApp.Contains('Traffic vehicle high-rate physics Hz') -and $studioApp.Contains('trafficSpawnPortals = {') -and $studioApp.Contains('trafficDensityRegions = {') -and $studioApp.Contains('trafficIncidents = {') -and $studioApp.Contains('trafficEnvironment = {') -and $studioApp.Contains('trafficDebug = {')) "STUDIO15 full-vehicle traffic option and spatial/operational data are published to Racing United"
Check ($studioGameplayRuntime.Contains('GetActiveTrafficSpawnPortals') -and $studioGameplayRuntime.Contains('GetTrafficDensityAt') -and $studioGameplayRuntime.Contains('GetActiveTrafficIncidents') -and $studioGameplayRuntime.Contains('GetTrafficEnvironmentConfiguration') -and $studioGameplayRuntime.Contains('GetTrafficDebugConfiguration')) "STUDIO15 RacingGameplay exposes traffic portal, density, incident, environment and debug queries"
Check ($trafficOperations.Contains('ReportIncident') -and $trafficOperations.Contains('ClearIncident') -and $trafficOperations.Contains('UpdateIncidents') -and $trafficOperations.Contains('incidentMatchesLink') -and $trafficOperations.Contains('incidentInfluence')) "STUDIO15 operational routing consumes authored and runtime incidents without relying on source comments"
Check ($trafficAgents.Contains('chooseStartPortal') -and $trafficAgents.Contains('portalAllowsProfile') -and $trafficAgents.Contains('GetTrafficDensityAt') -and $trafficAgents.Contains('getEnvironmentModifiers') -and $trafficAgents.Contains('buildIntersectionDemand') -and $trafficAgents.Contains('DebugCreateBreakdown')) "STUDIO15 traffic agents consume portals, density, weather, adaptive signal demand and runtime breakdowns"
Check ((Test-Path $trafficVehicleFactoryPath) -and $racingUnitedMain.Contains('Runtime/TrafficVehicleFactory.lua') -and $trafficVehicleFactory.Contains('Vehicle.Create(body') -and $trafficVehicleFactory.Contains('Vehicle.AddWheel') -and $trafficVehicleFactory.Contains('Vehicle.SetInputs') -and $trafficVehicleFactory.Contains('trafficVehicleHighRateHz')) "STUDIO15 opt-in FULL-tier backend creates real Heritage Vehicle traffic rather than only kinematic proxies"
Check ((Test-Path $trafficPanelPath) -and $racingUnitedMain.Contains('UI/Prototype/TrafficPanel.lua') -and $trafficPanel.Contains('LIVE TRAFFIC / NAVIGATION') -and $trafficPanel.Contains('SPAWN ONE AGENT') -and $trafficPanel.Contains('CREATE BREAKDOWN HERE') -and $trafficPanel.Contains('environmentSpeedFactor')) "STUDIO15 prototype UI exposes live traffic telemetry and debugging controls"

# STUDIO16 advanced traffic behavior/recovery: operational agent negotiation rather than only graph traversal.
Check ((HasWrittenFormatVersionAtLeast $studioAuthoringCpp 'HROAD' 7) -and $studioAuthoringHeader.Contains('TrafficBehaviorConfiguration') -and $studioAuthoringCpp.Contains('ADVANCEDBEHAVIOR')) "STUDIO16 HROAD v7 serializes advanced merge/priority/overtake/parking/recovery/collision behavior policy"
Check ($studioApp.Contains('ADVANCED TRAFFIC BEHAVIOR / RECOVERY') -and $studioApp.Contains('Zipper merge negotiation') -and $studioApp.Contains('Roundabout gap negotiation') -and $studioApp.Contains('Opportunistic overtaking') -and $studioApp.Contains('Automatic stuck recovery')) "STUDIO16 Traffic workspace exposes advanced live-agent behavior and recovery controls"
Check ($studioApp.Contains('trafficBehavior = {') -and $studioGameplayRuntime.Contains('GetTrafficBehaviorConfiguration')) "STUDIO16 advanced traffic behavior policy is compiled to Racing United and queryable at runtime"
Check ($trafficAgents.Contains('zipperMergeShouldYield') -and $trafficAgents.Contains('roundaboutShouldYield') -and $trafficAgents.Contains('stopDwellRemainingS') -and $trafficAgents.Contains('maybeReturnToDrivingLane')) "STUDIO16 traffic agents implement zipper merging, roundabout negotiation, stop dwell and overtake-return behavior"
Check ($trafficAgents.Contains('queueReleaseTimerS') -and $trafficAgents.Contains('parkingManeuver == "reverse"') -and $trafficAgents.Contains('recoveryTeleportSeconds') -and $trafficAgents.Contains('detectTrafficCollisions')) "STUDIO16 traffic agents implement queue discharge, staged parking, multi-stage stuck recovery and collision incidents"
Check ($trafficAgents.Contains('maybeDispatchEmergencyAgent') -and $trafficAgents.Contains('emergencyIncidentLookaheadM') -and $trafficPanel.Contains('Decision:') -and $trafficPanel.Contains('Recovery %s')) "STUDIO16 emergency incident dispatch and deep per-agent decision telemetry are exposed for debugging"

# STUDIO17 police / clandestine free-roam gameplay: HGAME-owned pursuit authoring,
# runtime heat/search/dispatch/roadblocks and dedicated live debugging.
$policeRuntimePath = Join-Path $Root "Modules\RacingUnited\Scripts\Runtime\PoliceGameplay.lua"
$policeRuntime = ReadText $policeRuntimePath
$policePanelPath = Join-Path $Root "Modules\RacingUnited\Scripts\UI\Prototype\PolicePanel.lua"
$policePanel = ReadText $policePanelPath
Check ((HasWrittenFormatVersionAtLeast $studioAuthoringCpp 'HGAME' 3) -and $studioAuthoringHeader.Contains('PoliceGameplayConfiguration') -and $studioAuthoringHeader.Contains('PolicePatrolZone') -and $studioAuthoringHeader.Contains('PoliceRoadblockSite') -and $studioAuthoringHeader.Contains('PoliceEscapeZone') -and $studioAuthoringHeader.Contains('ClandestineMeet')) "STUDIO17 HGAME v3 serializes police pursuit and clandestine free-roam authoring"
Check ($studioApp.Contains('POLICE / UNDERGROUND') -and $studioApp.Contains('+ PATROL ZONE') -and $studioApp.Contains('+ ROADBLOCK SITE') -and $studioApp.Contains('+ ESCAPE ZONE') -and $studioApp.Contains('+ CLANDESTINE MEET') -and $studioApp.Contains('PURSUIT / CLANDESTINE POLICY')) "STUDIO17 Gameplay workspace exposes police zones, roadblocks, escape zones, clandestine meets and pursuit policy"
Check ($studioApp.Contains('policeGameplay = {') -and $studioApp.Contains('policePatrolZones = {') -and $studioApp.Contains('policeRoadblockSites = {') -and $studioApp.Contains('policeEscapeZones = {') -and $studioApp.Contains('clandestineMeets = {')) "STUDIO17 police/clandestine authoring is compiled into Racing United runtime data"
Check ($studioGameplayRuntime.Contains('GetPoliceGameplayConfiguration') -and $studioGameplayRuntime.Contains('GetPolicePatrolCoverageAt') -and $studioGameplayRuntime.Contains('GetPoliceEscapeInfluenceAt') -and $studioGameplayRuntime.Contains('GetOpenClandestineMeets')) "STUDIO17 RacingGameplay exposes patrol, escape and clandestine meet queries"
Check ((Test-Path $policeRuntimePath) -and $racingUnitedMain.Contains('Runtime/PoliceGameplay.lua') -and $policeRuntime.Contains('ReportInfraction') -and $policeRuntime.Contains('dispatchPolice') -and $policeRuntime.Contains('selectRoadblock') -and $policeRuntime.Contains('automaticSpeedEnforcement') -and $policeRuntime.Contains('BeginClandestineEvent')) "STUDIO17 runtime implements witnessing/heat, dispatch, roadblocks, speed enforcement and clandestine-event heat"
Check ($trafficAgents.Contains('SpawnEmergencyUnit') -and $trafficAgents.Contains('AssignDestination') -and $racingUnitedLifecycle.Contains('RacingPolice.Start') -and $racingUnitedLifecycle.Contains('RacingPolice.FixedUpdate') -and $racingUnitedLifecycle.Contains('RacingPolice.Stop')) "STUDIO17 pursuit units reuse the traffic navigation stack and police lifecycle runs alongside vehicle/traffic simulation"
Check ((Test-Path $policePanelPath) -and $racingUnitedMain.Contains('UI/Prototype/PolicePanel.lua') -and $policePanel.Contains('POLICE / CLANDESTINE FREE-ROAM') -and $policePanel.Contains('REPORT SPEEDING') -and $policePanel.Contains('FORCE ESCAPE / SEARCH')) "STUDIO17 prototype UI exposes pursuit telemetry and deterministic debug controls"

# STUDIO18 event execution and exact-state section practice looping.
$raceEventsPath = Join-Path $Root "Modules\RacingUnited\Scripts\Runtime\RaceEvents.lua"
$practiceLoopPath = Join-Path $Root "Modules\RacingUnited\Scripts\Runtime\PracticeLoop.lua"
$racePanelPath = Join-Path $Root "Modules\RacingUnited\Scripts\UI\Prototype\RacePanel.lua"
$raceEvents = ReadText $raceEventsPath
$practiceLoop = ReadText $practiceLoopPath
$racePanel = ReadText $racePanelPath
$racingReplayPath = Join-Path $Root "Modules\RacingUnited\Scripts\Runtime\RacingReplay.lua"
$racingReplay = ReadText $racingReplayPath
Check ((HasWrittenFormatVersionAtLeast $studioAuthoringCpp 'HGAME' 4) -and $studioAuthoringHeader.Contains('EventExecutionConfiguration')) "STUDIO18 HGAME v4 serializes event-execution and practice-loop policy"
Check ((HasWrittenFormatVersionAtLeast $studioAuthoringCpp 'HRACE' 4) -and $studioAuthoringHeader.Contains('std::uint32_t layoutId = 0') -and $studioApp.Contains('Layout scope') -and $studioApp.Contains('layoutId=') -and $studioGameplayRuntime.Contains('MarkerAppliesToLayout') -and $raceEvents.Contains('markerAppliesToEvent')) "STUDIO18 HRACE v4 scopes timing/grid/pit markers per venue layout while preserving global markers"
Check ($studioApp.Contains('EVENT RUNTIME / PRACTICE') -and $studioApp.Contains('Enable runtime event execution') -and $studioApp.Contains('Loop end gate width m') -and $studioApp.Contains('practiceLoopRestoreGear')) "STUDIO18 Gameplay workspace exposes event execution and exact-state practice-loop authoring"
Check ($studioApp.Contains('eventExecution = {') -and $studioGameplayRuntime.Contains('GetEventExecutionConfiguration')) "STUDIO18 event execution policy is compiled into Racing United runtime data"
Check ((Test-Path $raceEventsPath) -and $racingUnitedMain.Contains('Runtime/RaceEvents.lua') -and $raceEvents.Contains('StartEvent') -and $raceEvents.Contains('processTimingGates') -and $raceEvents.Contains('processTrackLimits') -and $raceEvents.Contains('processPits') -and $raceEvents.Contains('SetFlag') -and $raceEvents.Contains('GetStandings')) "STUDIO18 runtime executes staging/countdown/timing/laps/track-limits/pits/flags/results and standings"
Check ((Test-Path $practiceLoopPath) -and $racingUnitedMain.Contains('Runtime/PracticeLoop.lua') -and $practiceLoop.Contains('Physics.LocalToGlobal') -and $practiceLoop.Contains('Physics.GlobalToLocal') -and $practiceLoop.Contains('GetBodyLinearVelocity') -and $practiceLoop.Contains('SetBodyLinearVelocity') -and $practiceLoop.Contains('CaptureStart') -and $practiceLoop.Contains('CaptureEnd')) "STUDIO18 practice loop captures floating-origin-safe exact entry state and restores velocity on repeated end-gate crossings"
Check ($racingUnitedLifecycle.Contains('RacingEvents.FixedUpdate') -and $racingUnitedLifecycle.Contains('RacingPracticeLoop.FixedUpdate') -and $racingUnitedLifecycle.Contains('RacingPracticeLoop.HandleInput')) "STUDIO18 event and practice-loop systems run alongside the existing vehicle/traffic/police lifecycle"
Check ((Test-Path $racePanelPath) -and $racingUnitedMain.Contains('UI/Prototype/RacePanel.lua') -and $racePanel.Contains('PORTAL-STYLE PRACTICE LOOP') -and $racePanel.Contains('STAGE / START SELECTED') -and $racePanel.Contains('CHEQUERED')) "STUDIO18 prototype UI exposes event lifecycle, race-control and practice-loop diagnostics"

# STUDIO19 competitors, grids and complete motorsport weekends.
$motorsportRuntimePath = Join-Path $Root "Modules\RacingUnited\Scripts\Runtime\MotorsportWeekend.lua"
$motorsportRuntime = ReadText $motorsportRuntimePath
Check ((HasWrittenFormatVersionAtLeast $studioAuthoringCpp 'HRACE' 5) -and $studioAuthoringHeader.Contains('SessionGridSource') -and $studioAuthoringHeader.Contains('timedRace') -and $studioAuthoringHeader.Contains('minimumPitServiceSeconds') -and $studioAuthoringHeader.Contains('classificationPercent')) "STUDIO19 HRACE v5 serializes timed/endurance, pit-service, classification and grid-source session rules"
Check ((HasWrittenFormatVersionAtLeast $studioAuthoringCpp 'HGAME' 5) -and $studioAuthoringHeader.Contains('MotorsportClass') -and $studioAuthoringHeader.Contains('MotorsportEntrant') -and $studioAuthoringHeader.Contains('MotorsportChampionship') -and $studioAuthoringHeader.Contains('MotorsportRound')) "STUDIO19 HGAME v5 serializes classes, entrants, championships and calendar rounds"
Check ($studioApp.Contains('COMPETITORS / SERIES') -and $studioApp.Contains('+ ENTRANT') -and $studioApp.Contains('+ CHAMPIONSHIP') -and $studioApp.Contains('Qualifying pace') -and $studioApp.Contains('Points scheme')) "STUDIO19 Gameplay workspace exposes competition roster and championship authoring"
Check ($studioApp.Contains('Timed race format') -and $studioApp.Contains('Time + one lap') -and $studioApp.Contains('Minimum pit-service seconds') -and $studioApp.Contains('Grid source')) "STUDIO19 Race session inspector exposes endurance and grid rules"
Check ($studioApp.Contains('motorsportClasses = {') -and $studioApp.Contains('motorsportEntrants = {') -and $studioApp.Contains('motorsportChampionships = {') -and $studioGameplayRuntime.Contains('GetEntrantsForEvent') -and $studioGameplayRuntime.Contains('GetChampionshipRounds')) "STUDIO19 competition authoring is compiled into Racing United runtime data"
Check ((Test-Path $motorsportRuntimePath) -and $racingUnitedMain.Contains('Runtime/MotorsportWeekend.lua') -and $motorsportRuntime.Contains('BuildGrid') -and $motorsportRuntime.Contains('qualifyingOrder') -and $motorsportRuntime.Contains('OnEventFinished') -and $motorsportRuntime.Contains('GetChampionshipStandings')) "STUDIO19 runtime builds grids, consumes qualifying/results and maintains championship standings"
Check ($raceEvents.Contains('Formation') -and $raceEvents.Contains('Rolling Start') -and $raceEvents.Contains('timedRaceExpired') -and $raceEvents.Contains('minimumPitServiceSeconds') -and $raceEvents.Contains('mandatory pit service not completed')) "STUDIO19 RacingEvents consumes formation/rolling starts, timed races and mandatory pit service"
Check ($racingUnitedLifecycle.Contains('RacingMotorsport.FixedUpdate') -and ($racePanel.Contains('STUDIO19 MOTORSPORT WEEKEND') -or $racePanel.Contains('STUDIO20 MOTORSPORT / RACING AI') -or $racePanel.Contains('STUDIO21 MOTORSPORT / FULL-PHYSICS RACING AI') -or $racePanel.Contains('STUDIO22 MOTORSPORT / COLLIDER-AWARE RACECRAFT') -or $racePanel.Contains('STUDIO23 MOTORSPORT / SOLVER-CONTACT STEWARDING')) -and $racePanel.Contains('REBUILD GRID') -and $racePanel.Contains('QUALIFYING ORDER')) "STUDIO19 motorsport runtime participates in fixed update and exposes live grid/weekend diagnostics"
Check ($studioApp.Contains('Event assignment') -and $studioApp.Contains('Competition class') -and $studioApp.Contains('Championship class') -and $studioApp.Contains('Calendar event')) "STUDIO19 competition relationships use named editor references instead of requiring raw IDs"
Check ($motorsportRuntime.Contains('roundPointKey') -and $motorsportRuntime.Contains('dropWorstRounds') -and $motorsportRuntime.Contains('poleBonus') -and $motorsportRuntime.Contains('fastestLapBonus') -and $motorsportRuntime.Contains('GetClassStandings')) "STUDIO19 championship runtime persists per-round scoring, bonuses, dropped rounds and class standings"

# STUDIO20 Racing AI intelligence, strategy and live decision debugging.
$racingAiPath = Join-Path $Root "Modules\RacingUnited\Scripts\Runtime\RacingAI.lua"
$racingAi = ReadText $racingAiPath
Check ((HasWrittenFormatVersionAtLeast $studioAuthoringCpp 'HGAME' 6) -and $studioAuthoringHeader.Contains('MotorsportAiConfiguration') -and $studioAuthoringHeader.Contains('racecraft') -and $studioAuthoringHeader.Contains('tireManagement') -and $studioAuthoringHeader.Contains('mistakeRatePerHour')) "STUDIO20 HGAME v6 persists global Racing AI policy and per-entrant racecraft/strategy personality"
Check ($studioApp.Contains('STUDIO20 RACING AI INTELLIGENCE') -and $studioApp.Contains('Opponent awareness') -and $studioApp.Contains('Wet-line selection') -and $studioApp.Contains('Pit/fuel/tire strategy') -and $studioApp.Contains('Preferred line bias')) "STUDIO20 Gameplay competition inspector exposes deep Racing AI authoring"
Check ($studioApp.Contains('motorsportAi = {') -and $studioApp.Contains('racecraft=') -and $studioGameplayRuntime.Contains('GetMotorsportAiConfiguration')) "STUDIO20 Racing AI authoring is compiled into generated Racing United runtime data"
Check ((Test-Path $racingAiPath) -and $racingUnitedMain.Contains('Runtime/RacingAI.lua') -and $racingAi.Contains('UpdateAgent') -and $racingAi.Contains('GetControlIntent') -and $racingAi.Contains('authoredSpeedAhead') -and $racingAi.Contains('opponentContext')) "STUDIO20 runtime owns a reusable Racing AI decision/control-intent layer"
Check ($racingAi.Contains('Slipstream') -and $racingAi.Contains('Overtake') -and $racingAi.Contains('Defending') -and $racingAi.Contains('Blue flag yield') -and $racingAi.Contains('Multi-class yield')) "STUDIO20 Racing AI handles slipstreaming, overtaking, defending, blue flags and multi-class negotiation"
Check ($racingAi.Contains('wetLineBlend') -and $racingAi.Contains('Fuel window') -and $racingAi.Contains('Tire wear') -and $racingAi.Contains('Mandatory pit stop') -and $racingAi.Contains('Recovering mistake')) "STUDIO20 Racing AI handles wet-line choice, tire/fuel strategy, mandatory stops and deterministic mistakes"
Check ($motorsportRuntime.Contains('RacingAI.UpdateAgent') -and $motorsportRuntime.Contains('aiSegments') -and $motorsportRuntime.Contains('wetSegments') -and $motorsportRuntime.Contains('beginAiPitService') -and $motorsportRuntime.Contains('GetAiTelemetry')) "STUDIO20 motorsport weekend consumes Racing AI decisions, authored dry/wet lines and AI pit service"
Check (($racePanel.Contains('STUDIO20 LIVE RACING AI DECISION DEBUG') -or $racePanel.Contains('STUDIO21 LIVE RACING AI CONTROL / PHYSICS DEBUG') -or $racePanel.Contains('STUDIO22 LIVE RACING AI / SPATIAL RACECRAFT DEBUG') -or $racePanel.Contains('STUDIO23 LIVE RACING AI / PHYSICAL INCIDENT EVIDENCE')) -and $racePanel.Contains('Decision:') -and $racePanel.Contains('Slipstream') -and $racePanel.Contains('Tire life')) "STUDIO20 Race prototype UI exposes live per-competitor Racing AI decision telemetry"

# STUDIO21 native Heritage Vehicle Racing AI control, physical race progress and grip/damage feedback.
$racingAiVehicleControllerPath = Join-Path $Root "Modules\RacingUnited\Scripts\Runtime\RacingAIVehicleController.lua"
$racingAiVehicleController = ReadText $racingAiVehicleControllerPath
Check ((HasWrittenFormatVersionAtLeast $studioAuthoringCpp 'HGAME' 7) -and $studioAuthoringHeader.Contains('fullPhysicsCompetitors') -and $studioAuthoringHeader.Contains('physicsHighRateHz') -and $studioAuthoringHeader.Contains('damagePitThreshold')) "STUDIO21 HGAME v7 persists full-physics Racing AI control, grip and damage policy"
Check ($studioApp.Contains('STUDIO21 FULL-PHYSICS RACING AI CONTROL') -and $studioApp.Contains('Use native Heritage Vehicle dynamics for physical competitors') -and $studioApp.Contains('Grip-aware braking / throttle') -and $studioApp.Contains('Track-limit-aware passing')) "STUDIO21 Gameplay inspector exposes native race-car control and safety tuning"
Check ($studioApp.Contains('fullPhysicsCompetitors=') -and $studioApp.Contains('physicsHighRateHz=') -and $studioApp.Contains('weatherForecastEnabled=')) "STUDIO21 full-physics Racing AI policy is compiled into generated Racing United data"
Check ((Test-Path $racingAiVehicleControllerPath) -and $racingUnitedMain.Contains('Runtime/RacingAIVehicleController.lua') -and $racingAiVehicleController.Contains('Vehicle.Create') -and $racingAiVehicleController.Contains('Vehicle.AddWheel') -and $racingAiVehicleController.Contains('Vehicle.SetInputs')) "STUDIO21 runtime provides an optional native Heritage Vehicle Racing AI backend"
Check ($racingAiVehicleController.Contains('GetWheelTelemetry') -and $racingAiVehicleController.Contains('slipRatio') -and $racingAiVehicleController.Contains('slipAngleDegrees') -and $racingAiVehicleController.Contains('mechanicalHealth')) "STUDIO21 native controller feeds tire grip/contact and collision damage back into Racing AI telemetry"
Check ($motorsportRuntime.Contains('ProjectAgentToRoute') -and $motorsportRuntime.Contains('lastPhysicalRouteDistance') -and $motorsportRuntime.Contains('updatePhysicalAgentMotion') -and $motorsportRuntime.Contains('fullPhysicsCount')) "STUDIO21 physical chassis speed and projected route position drive race progress while logical fallback remains"
Check ($motorsportRuntime.Contains('pitEntryMainDistance') -and $motorsportRuntime.Contains('pitExitMainDistance') -and $motorsportRuntime.Contains('pitServiceDistance') -and $motorsportRuntime.Contains('pitLapLineDistance') -and $motorsportRuntime.Contains('crossedRouteDistance')) "STUDIO21 full-physics competitors project authored Pit Entry/Exit/Box/StartFinish markers onto pit/main routes for service, lap counting and rejoin"
Check ($racingAi.Contains('forecastWetness') -and $racingAi.Contains('trackLimitSafetyM') -and $racingAi.Contains('Side-by-side spacing') -and $racingAi.Contains('Damage repair')) "STUDIO21 Racing AI adds weather forecasting, track-limit-aware spatial racecraft and damage strategy"
Check (($racePanel.Contains('STUDIO21 LIVE RACING AI CONTROL / PHYSICS DEBUG') -or $racePanel.Contains('STUDIO22 LIVE RACING AI / SPATIAL RACECRAFT DEBUG') -or $racePanel.Contains('STUDIO23 LIVE RACING AI / PHYSICAL INCIDENT EVIDENCE')) -and $racePanel.Contains('mechanical health') -and $racePanel.Contains('Cross-track') -and $racePanel.Contains('Weather forecast wetness')) "STUDIO21 Race prototype UI exposes physical control, grip, damage and forecast diagnostics"

# STUDIO22 collider-authoritative close-quarters racecraft, stewarding and physical feedback.
$racingAiRacecraftPath = Join-Path $Root "Modules\RacingUnited\Scripts\Runtime\RacingAIRacecraft.lua"
$racingAiRacecraft = ReadText $racingAiRacecraftPath
$collisionHeaderPath = Join-Path $Root "Engine\HeritageEngine\Physics\CollisionSystem.hpp"
$collisionCppPath = Join-Path $Root "Engine\HeritageEngine\Physics\CollisionSystem.cpp"
$physicsBindingHandlersPath = Join-Path $Root "Engine\HeritageEngine\Core\Modules\LuaBindings\Physics\LuaPhysicsBindingHandlers.hpp"
$physicsColliderBindingsPath = Join-Path $Root "Engine\HeritageEngine\Core\Modules\LuaBindings\Physics\LuaPhysicsColliderBindings.cpp"
$physicsQueryBindingsPath = Join-Path $Root "Engine\HeritageEngine\Core\Modules\LuaBindings\Physics\LuaPhysicsQueryBindings.cpp"
$physicsBindingRegistrationPath = Join-Path $Root "Engine\HeritageEngine\Core\Modules\LuaBindings\Physics\LuaPhysicsBindingRegistration.cpp"
$collisionHeader = ReadText $collisionHeaderPath
$collisionCpp = ReadText $collisionCppPath
$physicsBindingHandlers = ReadText $physicsBindingHandlersPath
$physicsColliderBindings = ReadText $physicsColliderBindingsPath
$physicsQueryBindings = ReadText $physicsQueryBindingsPath
$physicsBindingRegistration = ReadText $physicsBindingRegistrationPath
Check ((HasWrittenFormatVersionAtLeast $studioAuthoringCpp 'HGAME' 8) -and $studioAuthoringHeader.Contains('colliderBoundsAuthority') -and $studioAuthoringHeader.Contains('sweptEnvelopeSeconds') -and $studioAuthoringHeader.Contains('unsafeReleasePenaltySeconds') -and $studioAuthoringHeader.Contains('tireOptimalMinimumC')) "STUDIO22 HGAME v8 persists collider-authoritative spatial racecraft, stewarding and thermal/fuel policy"
Check ($studioApp.Contains('STUDIO22 COLLIDER-AUTHORITATIVE RACECRAFT / STEWARDING') -and $studioApp.Contains('Use body collision bounds as chassis footprint') -and $studioApp.Contains('Divebomb / braking-battle judgement') -and $studioApp.Contains('Unsafe pit-release stewarding')) "STUDIO22 Gameplay inspector exposes collider, close-racing and stewarding controls"
Check ($studioApp.Contains('colliderBoundsAuthority=') -and $studioApp.Contains('sweptEnvelopeSeconds=') -and $studioApp.Contains('fuelDensityKgPerLiter=') -and $studioApp.Contains('componentDamageStrategy=')) "STUDIO22 policy is compiled into generated Racing United gameplay data"
Check ($collisionHeader.Contains('BodyCollisionBounds') -and $collisionHeader.Contains('bodyCollisionBounds') -and $collisionCpp.Contains('Physics.GetBodyCollisionBounds') -and $collisionCpp.Contains('slot.record.trigger')) "STUDIO22 physics owns aggregate solid-collider body bounds and excludes trigger/sensor volumes"
Check ($physicsBindingHandlers.Contains('luaPhysicsGetBodyCollisionBounds') -and $physicsColliderBindings.Contains('bodyCollisionBounds') -and $physicsBindingRegistration.Contains('GetBodyCollisionBounds')) "STUDIO22 exposes Physics.GetBodyCollisionBounds to Lua as a read-only collision-authority query"
Check ((Test-Path $racingAiRacecraftPath) -and $racingUnitedMain.Contains('Runtime/RacingAIRacecraft.lua') -and $racingAiRacecraft.Contains('SetPhysicalFootprint') -and $racingAiRacecraft.Contains('predictedOverlap') -and $racingAiRacecraft.Contains('Divebomb aborted') -and $racingAiRacecraft.Contains('Switchback / crossover')) "STUDIO22 runtime predicts collider envelopes and handles side-by-side, divebomb and switchback racecraft"
Check ($racingAiRacecraft.Contains('maximumDefensiveMovesPerStraight') -and $racingAiRacecraft.Contains('Unsafe Release') -and $raceEvents.Contains('AddParticipantPenalty')) "STUDIO22 blocking and unsafe-release stewarding produce real participant time penalties"
Check ($racingAiVehicleController.Contains('Physics.GetBodyCollisionBounds') -and $racingAiVehicleController.Contains('tireTreadTemperatureC') -and $racingAiVehicleController.Contains('fuelDensityKgPerLiter') -and $racingAiVehicleController.Contains('componentHealth')) "STUDIO22 native Racing AI feeds collider bounds, tire temperature, fuel mass and component damage back into intelligence"
Check ($motorsportRuntime.Contains('tireTemperatureC=feedback') -and $motorsportRuntime.Contains('RacingAIRacecraft.GetTelemetry') -and $racingAi.Contains('Tire overheating') -and $racingAi.Contains('Component damage')) "STUDIO22 motorsport runtime closes physical thermal/component feedback into AI strategy and telemetry"
Check (($racePanel.Contains('STUDIO22 LIVE RACING AI / SPATIAL RACECRAFT DEBUG') -or $racePanel.Contains('STUDIO23 LIVE RACING AI / PHYSICAL INCIDENT EVIDENCE')) -and $racePanel.Contains('Collider footprint') -and $racePanel.Contains('Swept collision') -and $racePanel.Contains('Defensive moves') -and $racePanel.Contains('Components:')) "STUDIO22 Race prototype UI exposes live physical footprint, stewarding, thermal and component diagnostics"

# STUDIO23 solver-contact evidence, conservative incident classification and bounded steward review.
Check ((HasWrittenFormatVersionAtLeast $studioAuthoringCpp 'HGAME' 9) -and $studioAuthoringHeader.Contains('contactEvidenceEnabled') -and $studioAuthoringHeader.Contains('incidentMinimumNormalImpulseNs') -and $studioAuthoringHeader.Contains('retainedIncidentEvidence')) "STUDIO23 HGAME v9 persists solver-contact evidence thresholds, stewarding and retention policy"
Check ($studioApp.Contains('STUDIO23 SOLVER-CONTACT INCIDENT EVIDENCE / STEWARD REVIEW') -and $studioApp.Contains('Capture real solver-contact evidence') -and $studioApp.Contains('Severe contact impulse N s') -and $studioApp.Contains('Retained steward evidence events')) "STUDIO23 Gameplay inspector exposes physical incident evidence/steward controls"
Check ($studioApp.Contains('contactEvidenceEnabled=') -and $studioApp.Contains('incidentMinimumNormalImpulseNs=') -and $studioApp.Contains('severeContactPenaltySeconds=') -and $studioApp.Contains('retainedIncidentEvidence=')) "STUDIO23 incident policy is compiled into generated Racing United gameplay data"
Check ($physicsBindingHandlers.Contains('luaPhysicsGetBodyContact') -and $physicsQueryBindings.Contains('normalImpulseNs') -and $physicsQueryBindings.Contains('otherBody') -and $collisionHeader.Contains('BodyContactEvidence') -and $collisionHeader.Contains('bodyContactEvidence') -and $physicsQueryBindings.Contains('evidence.normal') -and $physicsBindingRegistration.Contains('GetBodyContact')) "STUDIO23 exposes resolved body contact evidence through Physics.GetBodyContact"
Check ($racingAiVehicleController.Contains('strongestBodyContact') -and $racingAiVehicleController.Contains('relativeClosingKmh') -and $racingAiVehicleController.Contains('contactZone') -and $racingAiVehicleController.Contains('normalImpulseNs')) "STUDIO23 native Racing AI derives strongest solver-contact evidence, closing speed and chassis contact zone"
Check ($motorsportRuntime.Contains('ReportPhysicalContact') -and $motorsportRuntime.Contains('otherBody') -and $racingAiRacecraft.Contains('classifyPhysicalIncident') -and $racingAiRacecraft.Contains('Rear-end contact') -and $racingAiRacecraft.Contains('Side-to-side contact')) "STUDIO23 motorsport resolves contacted race bodies and conservatively classifies physical incidents"
Check ($racingAiRacecraft.Contains('contactEvidenceCooldownSeconds') -and $racingAiRacecraft.Contains('GetIncidentLog') -and $racingAiRacecraft.Contains('retainedIncidentEvidence') -and $racingAiRacecraft.Contains('Severe Avoidable Contact')) "STUDIO23 suppresses duplicate manifold reports, retains bounded evidence and uses existing steward penalties"
Check ($racePanel.Contains('STUDIO23 LIVE RACING AI / PHYSICAL INCIDENT EVIDENCE') -and $racePanel.Contains('Solver contact') -and $racePanel.Contains('Last steward evidence') -and $racePanel.Contains('RECENT STEWARD EVIDENCE')) "STUDIO23 Race prototype UI exposes raw solver contact and retained steward evidence"

# STUDIO24 bounded incident replay and ghost steward review.
Check ((HasWrittenFormatVersionAtLeast $studioAuthoringCpp 'HGAME' 10) -and $studioAuthoringHeader.Contains('MotorsportReplayConfiguration') -and $studioAuthoringHeader.Contains('maximumIncidentClips') -and $studioAuthoringHeader.Contains('maximumRecordedCompetitors')) "STUDIO24 HGAME v10 persists bounded incident replay capture/review policy"
Check ($studioApp.Contains('STUDIO24 INCIDENT REPLAY / STEWARD GHOST REVIEW') -and $studioApp.Contains('Replay sample rate Hz') -and $studioApp.Contains('Incident pre-roll seconds') -and $studioApp.Contains('Maximum review ghost vehicles')) "STUDIO24 Gameplay inspector exposes incident replay sampling, retention and ghost-review controls"
Check ($studioApp.Contains('motorsportReplay = {') -and $studioApp.Contains('maximumRecordedCompetitors=') -and $studioGameplayRuntime.Contains('GetMotorsportReplayConfiguration')) "STUDIO24 replay policy is compiled into generated Racing United gameplay data"
Check ((Test-Path $racingReplayPath) -and $racingUnitedMain.Contains('Runtime/RacingReplay.lua') -and $racingReplay.Contains('rollingFrames') -and $racingReplay.Contains('MarkIncident') -and $racingReplay.Contains('postUntilTimeS') -and $racingReplay.Contains('maximumIncidentClips')) "STUDIO24 runtime maintains bounded pre/post-impact incident replay clips"
Check ($racingAiRacecraft.Contains('RacingReplay.MarkIncident') -and $motorsportRuntime.Contains('GetReplaySnapshot') -and $racingReplay.Contains('Physics.LocalToGlobal') -and $racingReplay.Contains('maximumRecordedCompetitors')) "STUDIO24 STUDIO23 incidents seal floating-origin-safe competitor replay snapshots"
Check ($racingReplay.Contains('Replay Ghost') -and $racingReplay.Contains('GlobalToLocal') -and $racingReplay.Contains('SetReviewOffset') -and $racingReplay.Contains('JumpToIncident') -and $racingReplay.Contains('reviewPlaying')) "STUDIO24 supports scrub/play incident review using non-physical ghost vehicles"
Check ($racingUnitedLifecycle.Contains('RacingReplay.FixedUpdate') -and $racingUnitedLifecycle.Contains('RacingReplay.Update') -and $raceEvents.Contains('RacingReplay.OnEventStarted') -and $raceEvents.Contains('RacingReplay.OnEventFinished')) "STUDIO24 replay recorder participates in race lifecycle and render-time ghost playback"
Check (($racePanel.Contains('STUDIO24 INCIDENT REPLAY / STEWARD GHOST REVIEW') -or $racePanel.Contains('STUDIO25 INCIDENT REPLAY / BROADCAST STEWARD REVIEW') -or $racePanel.Contains('STUDIO26 INCIDENT REPLAY / AUTHORED BROADCAST REVIEW') -or $racePanel.Contains('STUDIO27 INCIDENT REPLAY / STATIC + MOVING BROADCAST REVIEW')) -and $racePanel.Contains('PREV REPLAY') -and $racePanel.Contains('SHOW GHOSTS') -and $racePanel.Contains('Replay timeline') -and $racePanel.Contains('IMPACT')) "STUDIO24 Race prototype UI browses, scrubs and plays retained incident clips"

# STUDIO25 native FP64 replay/broadcast camera director and dark Studio chrome.
Check ((HasWrittenFormatVersionAtLeast $studioAuthoringCpp 'HGAME' 11) -and $studioAuthoringHeader.Contains('broadcastDirectorEnabled') -and $studioAuthoringHeader.Contains('incidentCameraDistanceM') -and $studioAuthoringHeader.Contains('helicopterCameraHeightM')) "STUDIO25 HGAME v11 persists replay/broadcast camera policy"
Check ($studioApp.Contains('STUDIO25 REPLAY / BROADCAST CAMERA DIRECTOR') -and $studioApp.Contains('Incident camera distance m') -and $studioApp.Contains('Trackside camera lead m') -and $studioApp.Contains('Helicopter camera height m')) "STUDIO25 Gameplay inspector exposes broadcast camera director controls"
Check ($studioApp.Contains('applyDarkNativeTitleBar') -and $studioApp.Contains('DWMWA_USE_IMMERSIVE_DARK_MODE') -and $studioApp.Contains('kCaptionColor')) "STUDIO25 Heritage Studio requests dark native Windows title-bar chrome"
Check ($vehicleCameraHeader.Contains('setDetachedWorldPose') -and $vehicleCameraCpp.Contains('setDetachedWorldPose') -and $luaCameraBindings.Contains('SetWorldPose') -and $luaCameraBindings.Contains('SetWorldViewActive')) "STUDIO25 Camera Lua API exposes direct FP64 world-space camera poses"
Check ($engineSimulation.Contains('detached/world-space camera authority is independent') -and $engineSimulation.Contains('vehicleCamera.detachedActive()')) "STUDIO25 world camera render authority no longer requires a live player chassis"
Check ($racingReplay.Contains('cameraModes=') -and $racingReplay.Contains('"Incident"') -and $racingReplay.Contains('"Trackside"') -and $racingReplay.Contains('"Chase"') -and $racingReplay.Contains('"Helicopter"') -and $racingReplay.Contains('updateReviewCamera') -and $racingReplay.Contains('Camera.SetWorldPose') -and $racingReplay.Contains('cameraSmoothing')) "STUDIO25 replay runtime auto-frames incidents using native world cameras"
Check ($racePanel.Contains('INCIDENT CAM') -and $racePanel.Contains('TRACKSIDE') -and $racePanel.Contains('CHASE CAM') -and $racePanel.Contains('HELICOPTER') -and $racePanel.Contains('CAM OFF')) "STUDIO25 Race UI exposes replay/broadcast camera modes"



# STUDIO26 HeritageEngine-parity dark chrome, Blender fly navigation and authored trackside broadcast cameras.
Check ($studioApp.Contains('glfwWindowHint(GLFW_DECORATED, GLFW_FALSE)') -and $studioApp.Contains('drawStudioWindowChrome') -and $studioApp.Contains('drawStudioResizeHandles') -and $studioApp.Contains('HERITAGE STUDIO')) "STUDIO26 Heritage Studio uses HeritageEngine-style undecorated GLFW + ImGui dark window chrome"
Check ($studioApp.Contains('ImGuiKey_GraveAccent') -and $studioApp.Contains('GLFW_CURSOR_DISABLED') -and $studioApp.Contains('FLY NAVIGATION') -and $studioApp.Contains('WASD move') -and $studioApp.Contains('RMB/Esc cancel')) "STUDIO26 shared 3D viewport supports Blender Shift+grave modal fly navigation"
Check ($studioApp.Contains('SET REPLAY CAMERA FROM CURRENT VIEW') -and $studioApp.Contains('Camera activation radius m') -and $studioAuthoringCpp.Contains('RaceMarkerType::ReplayCamera') -and $studioAuthoringCpp.Contains('value.radiusM = 120.0f')) "STUDIO26 Replay Camera markers can be authored directly from the current Studio view"
Check ($racingReplay.Contains('authoredTracksideCamera') -and $racingReplay.Contains('GetMarkersByType("Replay Camera"') -and $racingReplay.Contains('authoredCameraId') -and $racingReplay.Contains('previousAuthoredCameraId')) "STUDIO26 Trackside replay prefers applicable authored Replay Camera markers and cuts cleanly between stations"
Check (($racePanel.Contains('STUDIO26 INCIDENT REPLAY / AUTHORED BROADCAST REVIEW') -or $racePanel.Contains('STUDIO27 INCIDENT REPLAY / STATIC + MOVING BROADCAST REVIEW')) -and $racePanel.Contains('cameraSource') -and $racePanel.Contains('authoredCameraId')) "STUDIO26 Race replay UI reports authored versus procedural broadcast-camera source"


# STUDIO27 corrected Blender fly pitch and authored moving broadcast-camera splines.
Check ($studioApp.Contains('pitchDeg = std::clamp(pitchDeg + io.MouseDelta.y * 0.12f') -and $studioApp.Contains('ImGuiKey_GraveAccent')) "STUDIO27 Blender fly mouse pitch follows the requested non-inverted Studio convention"
Check ((HasWrittenFormatVersionAtLeast $studioAuthoringCpp 'HRACE' 6) -and $studioAuthoringHeader.Contains('BroadcastCameraPath') -and $studioAuthoringHeader.Contains('BroadcastCameraNode') -and $studioAuthoringCpp.Contains('CAMERA_PATH') -and $studioAuthoringCpp.Contains('CAMERA_NODE')) "STUDIO27 HRACE v6 persists moving broadcast-camera paths and control points"
Check ($studioApp.Contains('TV CAMERAS') -and $studioApp.Contains('ADD CONTROL POINT FROM CURRENT VIEW') -and $studioApp.Contains('SNAP POINT TO CURRENT VIEW') -and $studioApp.Contains('catmullRom')) "STUDIO27 Heritage Studio authors and previews smooth moving TV camera paths from Blender-style fly views"
Check ($studioApp.Contains('broadcastCameraPaths = {') -and $studioGameplayRuntime.Contains('GetBroadcastCameraPaths') -and $studioGameplayRuntime.Contains('GetBroadcastCameraPathNodes')) "STUDIO27 generated gameplay schema publishes camera paths and runtime lookup helpers"
Check ($racingReplay.Contains('authoredBroadcastPath') -and $racingReplay.Contains('evaluateBroadcastPath') -and $racingReplay.Contains('state.cameraMode=="Spline"') -and $racingReplay.Contains('authoredCameraPathId')) "STUDIO27 replay director evaluates authored moving camera splines with procedural fallback"
Check ($racePanel.Contains('MOVING TV') -and $racePanel.Contains('authoredCameraPathId') -and $racePanel.Contains('STUDIO27 INCIDENT REPLAY / STATIC + MOVING BROADCAST REVIEW')) "STUDIO27 replay UI exposes moving authored TV camera review"

# STUDIO28 shared free-roam traffic cones and autoslalom/gymkhana course authority.
Check ((HasWrittenFormatVersionAtLeast $studioAuthoringCpp 'HRACE' 7) -and $studioAuthoringHeader.Contains('CourseCone') -and $studioAuthoringHeader.Contains('ConeCourseGate') -and $studioAuthoringCpp.Contains('CONE_CONFIG') -and $studioAuthoringCpp.Contains('CONE_GATE')) "STUDIO28 HRACE v7 persists cone policy, physical/semantic cones and ordered course elements"
Check ((HasWrittenFormatVersionAtLeast $studioAuthoringCpp 'HGAME' 12) -and $studioAuthoringCpp.Contains('GameEventType::Autoslalom') -and $studioAuthoringCpp.Contains('GameEventType::Gymkhana')) "STUDIO28 HGAME v12 appends Autoslalom/Gymkhana event types without retiring historical events"
Check ($studioApp.Contains('CONE COURSES') -and $studioApp.Contains('FIT GATE TO REFERENCED CONES') -and $studioApp.Contains('Default cone GLB') -and $studioApp.Contains('ConeTrafficMode::CloseRoad') -and $studioApp.Contains('Stop Box')) "STUDIO28 Race workspace authors cone overlays, traffic meaning and invisible course elements"
Check ($studioApp.Contains('GENERATE ALTERNATING SLALOM') -and $studioApp.Contains('DUPLICATE SELECTED CONE LINE / TAPER') -and $studioApp.Contains('360 LEFT') -and $studioApp.Contains('360 RIGHT')) "STUDIO28 quick builders cover course pieces plus persistent free-roam cone lines/tapers"
Check ($studioApp.Contains('ImVec2 center{}, left{}, rightScreen{}, arrow{}') -and -not $studioApp.Contains('ImVec2 center{}, left{}, right{}, arrow{}')) "STUDIO28B course-gate viewport keeps world-space right axis distinct from screen-space right endpoint"
# STUDIO31 replaces the STUDIO30 six-lattice ImGui overlay with a depth-aware
# procedural floor pass inside the Scene GLB framebuffer.
Check ($studioScenePreview.Contains('bool StudioScenePreview::ensureGridProgram') -and $studioScenePreview.Contains('metresPerPixel') -and $studioScenePreview.Contains('fineStep') -and $studioScenePreview.Contains('coarseStep') -and $studioScenePreview.Contains('fwidth(coord)')) "STUDIO31 Scene preview owns a derivative-filtered adaptive procedural infinite grid"
Check ($studioScenePreview.Contains('gl_FragDepth') -and $studioScenePreview.Contains('glDepthFunc(GL_LEQUAL)') -and $studioScenePreview.Contains('gridVisible && m_gridProgram && m_gridVao')) "STUDIO31 grid writes scene depth instead of drawing always-on-top lines over geometry"
Check ($studioScenePreview.Contains('axisMask(world.z)') -and $studioScenePreview.Contains('axisMask(world.x)') -and $studioScenePreview.Contains('horizonFade')) "STUDIO31 X/Z world axes are analytic infinite shader lines with grazing-angle fade"
Check ($studioApp.Contains('previewCamera(view), gridVisible') -and $studioApp.Contains('Do not draw a second always-on-top') -and $studioApp.Contains('STUDIO31 fallback')) "STUDIO31 Studio viewport routes scene-backed grids through the preview pass and retains a single-scale empty-view fallback"
Check ($studioApp.Contains('coneCourse = {') -and $studioApp.Contains('courseCones = {') -and $studioApp.Contains('coneCourseGates = {') -and $studioGameplayRuntime.Contains('GetConeCourseConfiguration') -and $studioGameplayRuntime.Contains('GetConeCourseGates')) "STUDIO28 generated StudioGameplay schema publishes cone/course data and runtime lookup helpers"
Check ((Test-Path $coneCoursePath) -and $racingUnitedMain.Contains('Runtime/ConeCourse.lua') -and $coneCourse.Contains('EvaluateGateCrossing') -and $coneCourse.Contains('Turnaround Left') -and $coneCourse.Contains('Stop Box') -and $coneCourse.Contains('360 Circle Left') -and $coneCourse.Contains('ResetActiveEventCones')) "STUDIO28 runtime owns deterministic gate/slalom/turnaround/stop-box/360 progression and cone reset"
Check ($coneCourse.Contains('GetBodyContact') -and $coneCourse.Contains('normalImpulseNs') -and $coneCourse.Contains('Displaced') -and $coneCourse.Contains('Knocked Down') -and $coneCourse.Contains('RacingReplay.MarkIncident')) "STUDIO28 cone strikes reuse solver contact evidence, displacement/knock-down rules and replay bookmarks"
Check ($trafficOperations.Contains('RacingConeCourse.ApplyTrafficControls') -and $coneCourse.Contains('Guide / Discourage') -and $coneCourse.Contains('Close Lane') -and $coneCourse.Contains('Close Road') -and $coneCourse.Contains('routeCostMultiplier')) "STUDIO28 persistent/event cone controls guide, slow or close existing free-roam traffic links"
Check ($raceEvents.Contains('Autoslalom') -and $raceEvents.Contains('Gymkhana') -and $raceEvents.Contains('RacingConeCourse.ProcessEvent') -and $raceEvents.Contains('CommitPersonalBest') -and $raceEvents.Contains('best_time_s') -and $racePanel.Contains('PB delta') -and $racePanel.Contains('RESET EVENT CONES')) "STUDIO28 autoslalom/gymkhana participates in countdown, penalties, coherent PB splits/deltas, results and Race playtest UI"
Check ($racingUnitedLifecycle.Contains('RacingConeCourse.Start') -and $racingUnitedLifecycle.Contains('RacingConeCourse.Stop') -and $racingUnitedLifecycle.Contains('RacingConeCourse.FixedUpdate')) "STUDIO28 cone world participates in prototype scene lifecycle and fixed-step physics"
