param(
    [string]$Root = "",
    [string]$Configuration = "unknown",
    [string]$Milestone = "29F"
)

$ErrorActionPreference = "Stop"

if ([string]::IsNullOrWhiteSpace($Root)) {
    $Root = (Resolve-Path (Join-Path $PSScriptRoot "..")).Path
} else {
    $Root = (Resolve-Path $Root).Path
}

function Escape-CppString([string]$Value) {
    if ($null -eq $Value) { return "" }
    return $Value.Replace("\", "\\").Replace('"', '\"').Replace("`r", "").Replace("`n", " ")
}

$commit = "unavailable"
$dirty = "unknown"
$git = Get-Command git -ErrorAction SilentlyContinue
if ($null -ne $git) {
    try {
        $candidate = (& $git.Source -C $Root rev-parse --short=12 HEAD 2>$null | Select-Object -First 1)
        if (-not [string]::IsNullOrWhiteSpace($candidate)) {
            $commit = $candidate.Trim()
            $status = (& $git.Source -C $Root status --porcelain 2>$null)
            $dirty = if ($status) { "dirty" } else { "clean" }
        }
    } catch {
        $commit = "unavailable"
        $dirty = "unknown"
    }
}

$generatedUtc = [DateTime]::UtcNow.ToString("yyyy-MM-ddTHH:mm:ss.fffZ")
$headerPath = Join-Path $Root "Engine\HeritageEngine\Core\Diagnostics\GeneratedBuildIdentity.hpp"
$reportRoot = Join-Path $Root "Build\Reports"
New-Item -ItemType Directory -Force -Path (Split-Path $headerPath) | Out-Null
New-Item -ItemType Directory -Force -Path $reportRoot | Out-Null

$header = @"
#pragma once

// Generated by Tools/GenerateBuildIdentity.ps1. Do not edit by hand.
namespace heritage::diagnostics::generated {
inline constexpr const char* kMilestone = "$(Escape-CppString $Milestone)";
inline constexpr const char* kGitCommit = "$(Escape-CppString $commit)";
inline constexpr const char* kGitDirty = "$(Escape-CppString $dirty)";
inline constexpr const char* kGeneratedUtc = "$(Escape-CppString $generatedUtc)";
inline constexpr const char* kRequestedConfiguration = "$(Escape-CppString $Configuration)";
}
"@

[IO.File]::WriteAllText($headerPath, $header, [Text.UTF8Encoding]::new($false))

$identityReport = @(
    "milestone=$Milestone",
    "requested_configuration=$Configuration",
    "git_commit=$commit",
    "git_dirty=$dirty",
    "generated_utc=$generatedUtc",
    "header=$headerPath"
) -join [Environment]::NewLine
[IO.File]::WriteAllText((Join-Path $reportRoot "BuildIdentity.txt"), $identityReport + [Environment]::NewLine, [Text.UTF8Encoding]::new($false))

Write-Host "Generated build identity: milestone=$Milestone configuration=$Configuration git=$commit dirty=$dirty"
