-- Racing United - modular Lua entry point.
-- Each included file executes inside this module's isolated Lua environment.
-- Heritage Engine watches every .lua file under Scripts and hot-reloads when any changes.

local function Include(relativePath)
    local ok, message = Script.Include(relativePath)
    if not ok then
        error(message or ("Could not include Lua file: " .. relativePath), 0)
    end
end

Include("Runtime/State.lua")
Include("Runtime/Common.lua")
Include("Runtime/PhysicsDemo.lua")
Include("Runtime/SurfaceDemo.lua")
Include("Runtime/ScenePresets.lua")
Include("Runtime/PlayerWorld.lua")
Include("Vehicles/Presets/Tires/PrototypeRoad.lua")
Include("Vehicles/Definitions/PrototypeCar.lua")
Include("Vehicles/State.lua")
Include("Vehicles/Visuals.lua")
Include("Vehicles/VisualWheels.lua")
Include("Vehicles/Input.lua")
Include("Vehicles/Formatting.lua")
Include("Vehicles/Tuning.lua")
Include("Vehicles/Factory.lua")
Include("Vehicles/Telemetry.lua")
Include("Vehicles/Lifecycle.lua")
Include("Runtime/PhysicsStartup.lua")
Include("Runtime/Lifecycle.lua")
Include("UI/MainScreen.lua")
Include("UI/SafetyNetPanel.lua")
Include("UI/Vehicle/DrivePanel.lua")
Include("UI/Vehicle/Visual/BodyPanel.lua")
Include("UI/Vehicle/Visual/WheelsPanel.lua")
Include("UI/Vehicle/VisualPanel.lua")
Include("UI/Vehicle/SurfacesPanel.lua")
Include("UI/Vehicle/Tires/ProfilesPanel.lua")
Include("UI/Vehicle/Tires/BasicPanel.lua")
Include("UI/Vehicle/Tires/CurvePanel.lua")
Include("UI/Vehicle/Tires/LivePanel.lua")
Include("UI/Vehicle/TiresPanel.lua")
Include("UI/Vehicle/DrivetrainPanel.lua")
Include("UI/Vehicle/DriverAidsPanel.lua")
Include("UI/Vehicle/TelemetryPanel.lua")
Include("UI/VehicleDebugPanel.lua")
Include("UI/Physics/WorldPanel.lua")
Include("UI/Physics/SuspensionPanel.lua")
Include("UI/Physics/QueriesPanel.lua")
Include("UI/Physics/BodyPanel.lua")
Include("UI/Prototype/PhysicsPanel.lua")
Include("UI/Prototype/EntityPanel.lua")
Include("UI/Prototype/ModulePanel.lua")
Include("UI/Prototype/ScenePanel.lua")
Include("UI/Prototype/SafetyPanel.lua")
Include("UI/PrototypeScreen.lua")
Include("UI/AboutScreen.lua")
Include("UI/UiLifecycle.lua")
